# Generated by Django 3.1.3 on 2020-11-11 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(1, 'But'), (2, 'Gamelle'), (3, 'Contre son camp'), (4, 'Lobe'), (5, 'Pas fait exprès')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'Avant'), (2, 'Defence'), (3, 'Goal')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatMyBallsApi.goaltype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatMyBallsApi.playerposition')),
            ],
        ),
    ]
