# Generated by Django 3.1.3 on 2020-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatMyBallsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltype',
            name='label',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='playerposition',
            name='position',
            field=models.CharField(max_length=60),
        ),
    ]
