# Generated by Django 3.1.3 on 2020-11-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StatMyBallsApi', '0003_goal_goal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_date',
        ),
    ]
