# Generated by Django 3.1.7 on 2021-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatMyBallsApi', '0006_auto_20210325_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_bounce_out',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
