# Generated by Django 3.1.7 on 2021-03-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatMyBallsApi', '0007_goal_is_bounce_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
