# Generated by Django 3.1.3 on 2020-11-11 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StatMyBallsApi', '0004_remove_goal_goal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='goal_date'),
            preserve_default=False,
        ),
    ]
